#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

OUT="${1:-docs/status/devon-project-index.md}"
mkdir -p "$(dirname "$OUT")"
TMP="$(mktemp)"

write_section() {
  printf '\n## %s\n\n' "$1"
}

write_command_block() {
  local lang="$1"
  shift
  printf '```%s\n' "$lang"
  "$@" || true
  printf '```\n'
}

write_package_scripts() {
  node -e '
const fs = require("fs");
const files = ["package.json", "openclaw/package.json", "worker/package.json"];
for (const file of files) {
  if (!fs.existsSync(file)) continue;
  const pkg = JSON.parse(fs.readFileSync(file, "utf8"));
  console.log(`### ${file}`);
  const scripts = pkg.scripts || {};
  const names = Object.keys(scripts).sort();
  if (!names.length) {
    console.log("- none");
  } else {
    for (const name of names) console.log(`- npm run ${name}: ${scripts[name]}`);
  }
  console.log("");
}
'
}

write_docs_files() {
  find docs -type f \
    ! -name '*.log' \
    ! -name '*.tmp' \
    | sort \
    | sed 's#^#- #'
}

write_major_dirs() {
  find . -maxdepth 2 -type d \
    \( -path './.git' \
    -o -path './node_modules' \
    -o -path './dist' \
    -o -path './worker/node_modules' \
    -o -path './.pytest_cache' \
    -o -path './.claude' \
    -o -path './.openclaw' \
    -o -name '__pycache__' \
    \) -prune \
    -o -type d -print \
    | sed 's#^\./##' \
    | grep -v '^\.$' \
    | sort \
    | head -80 \
    | sed 's#^#- #'
}

write_todos() {
  if command -v rg >/dev/null 2>&1; then
    rg -n '\b(TODO|FIXME)\b' . \
      --glob '!node_modules/**' \
      --glob '!worker/node_modules/**' \
      --glob '!dist/**' \
      --glob '!coverage/**' \
      --glob '!.pytest_cache/**' \
      --glob '!**/__pycache__/**' \
      --glob '!*.log' \
      --glob '!package-lock.json' \
      --glob '!worker/package-lock.json' \
      --glob '!openclaw/package-lock.json' \
      --glob '!scripts/devon_index_project.sh' \
      --glob '!docs/status/devon-project-index.md' \
      --glob '!docs/status/devon-morning-brief-sample.md' \
      --glob '!**/credentials.json' \
      --glob '!**/token.json' \
      --glob '!**/.env*' \
      | head -80 \
      || true
  else
    find . \
      \( -path './node_modules' \
      -o -path './worker/node_modules' \
      -o -path './dist' \
      -o -path './coverage' \
      -o -path './.pytest_cache' \
      -o -name '__pycache__' \
      \) -prune \
      -o -type f \
      ! -name '*.log' \
      ! -name 'package-lock.json' \
      ! -name 'credentials.json' \
      ! -name 'token.json' \
      ! -name '.env' \
      ! -path './scripts/devon_index_project.sh' \
      ! -path './docs/status/devon-project-index.md' \
      ! -path './docs/status/devon-morning-brief-sample.md' \
      -print \
      | xargs grep -nE '\b(TODO|FIXME)\b' 2>/dev/null \
      | head -80 \
      || true
  fi
}

write_david_artifacts() {
  for dir in design_outputs design_memory; do
    [ -d "$dir" ] || continue
    find "$dir" -type f \
      ! -name '*.log' \
      ! -name '.launchd*' \
      | sort
  done | head -80 | sed 's#^#- #'
}

write_generated_artifacts() {
  for dir in docs/dashboard/data public/data public/pencil-screenshots dist; do
    [ -d "$dir" ] || continue
    echo "- $dir/"
    find "$dir" -maxdepth 2 -type f \
      ! -name '*.log' \
      | sort \
      | head -20 \
      | sed 's#^#  - #'
  done
}

{
  echo "# Devon Project Index"
  echo
  echo "Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo
  echo "This artifact is generated by \`scripts/devon_index_project.sh\`. It lists paths"
  echo "and commands only; it must not include secrets, credentials, .env contents,"
  echo "tokens, private family data, or large raw logs."

  write_section "Repository"
  echo "- Name: $(basename "$ROOT")"
  echo "- Branch: $(git branch --show-current || echo unknown)"
  echo "- Latest commit: $(git log -1 --pretty=format:'%h %ad %s' --date=short || echo unknown)"

  write_section "Current Git Status"
  write_command_block text git status --short --branch

  write_section "Changed Files"
  changed="$(git status --short | sed 's#^#- #')"
  if [ -n "$changed" ]; then
    printf '%s\n' "$changed"
  else
    echo "- none"
  fi

  write_section "Major Directories"
  write_major_dirs

  write_section "Package Scripts"
  write_package_scripts

  write_section "Likely Test And Gate Commands"
  echo "- npm run validate:devon"
  echo "- npm test"
  echo "- npm run build"
  echo "- npm --prefix openclaw run eval"
  echo "- npm --prefix worker run dev"

  write_section "Docs Files"
  write_docs_files

  write_section "TODO And FIXME Comments"
  todo_output="$(write_todos)"
  if [ -n "$todo_output" ]; then
    printf '```text\n%s\n```\n' "$todo_output"
  else
    echo "- none found"
  fi

  write_section "David Design Artifacts"
  david_output="$(write_david_artifacts)"
  if [ -n "$david_output" ]; then
    printf '%s\n' "$david_output"
  else
    echo "- none found"
  fi

  write_section "Known Generated Artifacts"
  generated_output="$(write_generated_artifacts)"
  if [ -n "$generated_output" ]; then
    printf '%s\n' "$generated_output"
  else
    echo "- none found"
  fi
} > "$TMP"

mv "$TMP" "$OUT"
echo "$OUT"
